# Generated by Django 2.2.12 on 2022-07-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ai_info',
            },
        ),
        migrations.CreateModel(
            name='Egg_Meat_price',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('meat_ab2', models.CharField(max_length=10)),
                ('meat_l2', models.CharField(max_length=10)),
                ('meat_sout', models.CharField(max_length=10)),
                ('egg', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'egg_meat_price',
            },
        ),
        migrations.CreateModel(
            name='Feed_price',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('corn_tc', models.CharField(max_length=10)),
                ('corn_k', models.CharField(max_length=10)),
                ('soy_c', models.CharField(max_length=10)),
                ('soy_b', models.CharField(max_length=10)),
                ('cornFlour_b', models.CharField(max_length=10)),
                ('soyFlour', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'feed_price',
            },
        ),
    ]
