# Generated by Django 2.2.12 on 2022-07-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEmei',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'emei_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleFaith',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'faith_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleHuadong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'huadong_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleKinmen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'kinmen_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleNagoya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'nagoya_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleSilkie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'silkie_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleTaiwan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'Taiwan_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleTakezaki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'takezaki_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleZaki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300, verbose_name='連接')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.CharField(max_length=200, verbose_name='資訊')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('adviser', models.CharField(max_length=50, verbose_name='指導教授')),
            ],
            options={
                'db_table': 'zaki_article',
            },
        ),
    ]
