# Generated by Django 2.2.12 on 2022-08-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='種類')),
                ('title', models.CharField(max_length=20, verbose_name='文章標題')),
                ('species', models.CharField(max_length=10, verbose_name='品種')),
                ('content', models.CharField(max_length=200, verbose_name='文章內容')),
                ('male_pic', models.ImageField(null=True, upload_to='avatar')),
                ('female_pic', models.ImageField(null=True, upload_to='avatar')),
                ('weight_info', models.CharField(max_length=20, verbose_name='16週齡體重')),
                ('first_egg_info', models.CharField(max_length=10, verbose_name='初產日齡')),
                ('total_egg_info', models.CharField(max_length=10, verbose_name='初產至40週齡總產蛋數')),
            ],
            options={
                'db_table': 'chicken_info',
            },
        ),
    ]
