# Generated by Django 2.2.12 on 2022-07-31 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用戶名')),
                ('nickname', models.CharField(max_length=30, verbose_name='暱稱')),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, verbose_name='手機號碼')),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('info', models.CharField(default='', max_length=150, verbose_name='個人簡介')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
        migrations.CreateModel(
            name='GithubProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=32, unique=True, verbose_name='Gituid')),
                ('access_token', models.CharField(max_length=200, verbose_name='權限token')),
                ('user_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'user_github_profile',
            },
        ),
    ]
